-- =====================================================
-- RETAIL BANKING SCHEMA 
-- =====================================================

-- Drop existing tables if they exist (in correct order due to FK dependencies)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE LOCKER_RENTAL CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE LOCKER CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE LOAN_REPAYMENT CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE LOAN_ACCOUNT CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE LOAN_APPLICATION CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE LOAN_TYPE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CARD CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Drop TRANSACTION first (it might have different name due to previous errors)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE BANK_TRANSACTION CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE "TRANSACTION" CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ACCOUNT_HOLDER CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ACCOUNT CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ACCOUNT_TYPE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE USER_AUTH CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CUSTOMER CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE BRANCH CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Drop sequences
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE customer_seq';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE user_auth_seq';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE branch_seq';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE account_type_seq';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE account_seq';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE transaction_seq';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE card_seq';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE loan_type_seq';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE loan_application_seq';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE loan_account_seq';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE loan_repayment_seq';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE locker_seq';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE locker_rental_seq';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- =====================================================
-- CREATE SEQUENCES
-- =====================================================

CREATE SEQUENCE customer_seq START WITH 1001 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE user_auth_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE branch_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE account_type_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE account_seq START WITH 50001 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE transaction_seq START WITH 100001 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE card_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE loan_type_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE loan_application_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE loan_account_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE loan_repayment_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE locker_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE locker_rental_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;



-- =====================================================
-- TABLE: CUSTOMER
-- =====================================================
CREATE TABLE CUSTOMER(
     CUSTOMER_ID INT PRIMARY KEY,
     CNIC VARCHAR2(13) NOT NULL UNIQUE CHECK(LENGTH(CNIC) = 13),
     FIRST_NAME VARCHAR2(30) NOT NULL,
     LAST_NAME VARCHAR2(30) NOT NULL,
     DATE_OF_BIRTH DATE NOT NULL,
     AGE INT, --will be calculated by trigger
     PHONE_NUMBER VARCHAR2(15) CHECK (LENGTH(PHONE_NUMBER) = 11), -- Changed to 11 for Pakistani numbers
     ADDRESS VARCHAR2(100),
     EMAIL VARCHAR2(100) UNIQUE
);

-- Create index on EMAIL for faster lookups
CREATE INDEX idx_customer_email ON CUSTOMER(EMAIL);

-- =====================================================
-- TABLE: USER_AUTH
-- =====================================================
CREATE TABLE USER_AUTH(
    USER_ID INT PRIMARY KEY,
    CUSTOMER_ID INT NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'Active' CHECK (STATUS IN ('Active', 'Locked', 'Suspended')),
    CONSTRAINT FK_USER_CUST FOREIGN KEY (CUSTOMER_ID) 
    REFERENCES CUSTOMER(CUSTOMER_ID) ON DELETE CASCADE
);

-- =====================================================
-- TABLE: BRANCH
-- =====================================================
CREATE TABLE BRANCH(
    BRANCH_ID INT PRIMARY KEY,
    BRANCH_NAME VARCHAR2(50) NOT NULL UNIQUE,
    LOCATION VARCHAR2(50)
);

-- =====================================================
-- TABLE: ACCOUNT_TYPE
-- =====================================================
CREATE TABLE ACCOUNT_TYPE(
   TYPE_ID INT PRIMARY KEY,
   TYPE_NAME VARCHAR2(40) NOT NULL UNIQUE,
   MIN_BALANCE DECIMAL(15,2) DEFAULT 0,
   MONTHLY_FEE DECIMAL(10,2) DEFAULT 0
);

-- =====================================================
-- TABLE: ACCOUNT
-- ===========================================
CREATE TABLE ACCOUNT(
   ACCOUNT_ID INT PRIMARY KEY,
   BRANCH_ID INT NOT NULL,
   TYPE_ID INT NOT NULL,
   ACCOUNT_NUMBER VARCHAR2(20) NOT NULL UNIQUE,
   BALANCE DECIMAL(15,2) DEFAULT 0 CHECK (BALANCE >= 0),
   ACCOUNT_MODE VARCHAR2(20) CHECK (ACCOUNT_MODE IN ('Individual', 'Joint')),
   STATUS VARCHAR2(20) DEFAULT 'Active' CHECK (STATUS IN ('Active', 'Dormant', 'Frozen', 'Closed')),
   OPENED_DATE DATE DEFAULT SYSDATE,
   CONSTRAINT FK_ACC_BRANCH FOREIGN KEY (BRANCH_ID) 
   REFERENCES BRANCH(BRANCH_ID),
   CONSTRAINT FK_ACC_TYPE FOREIGN KEY (TYPE_ID) 
   REFERENCES ACCOUNT_TYPE(TYPE_ID)
);

-- =====================================================
-- TABLE: ACCOUNT_HOLDER (Bridge Table of CUSTOMER and ACCOUNT)
-- =====================================================
CREATE TABLE ACCOUNT_HOLDER(
   ACCOUNT_ID INT,
   CUSTOMER_ID INT,
   HOLDER_TYPE VARCHAR2(25) NOT NULL CHECK (HOLDER_TYPE IN ('Primary', 'Secondary', 'Joint')),
   CONSTRAINT AH_PK PRIMARY KEY (ACCOUNT_ID, CUSTOMER_ID),
   CONSTRAINT FK_AH_ACC FOREIGN KEY (ACCOUNT_ID) 
   REFERENCES ACCOUNT(ACCOUNT_ID) ON DELETE CASCADE,
   CONSTRAINT FK_AH_CUST FOREIGN KEY (CUSTOMER_ID) 
   REFERENCES CUSTOMER(CUSTOMER_ID) ON DELETE CASCADE
);

-- =====================================================
-- TABLE: TRANSACTION
-- ===================================================
CREATE TABLE BANK_TRANSACTION(
   TRANSACTION_ID INT PRIMARY KEY,
   ACCOUNT_ID INT NOT NULL,
   RECIPIENT_ACCOUNT_ID INT NOT NULL,
   RECIPIENT_ACCOUNT_NAME VARCHAR2(100) NOT NULL,
   TRANSACTION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   AMOUNT DECIMAL(15,2) NOT NULL CHECK (AMOUNT > 0),
   TRANSACTION_TYPE VARCHAR2(20) NOT NULL CHECK (TRANSACTION_TYPE IN ('Deposit', 'Transfer', 'Fee', 'Withdrawal')), -- Added Withdrawal
   TRANSACTION_MODE VARCHAR2(30) CHECK (TRANSACTION_MODE IN ('Cash', 'Cheque', 'Online', 'Mobile')), -- Changed from MODE
   BALANCE_REMAINING DECIMAL(15,2) NOT NULL,
   CONSTRAINT FK_TRN_ACC FOREIGN KEY (ACCOUNT_ID) 
   REFERENCES ACCOUNT(ACCOUNT_ID) ON DELETE CASCADE
);
-- =====================================================
-- TABLE: CARD
-- ===================================================
CREATE TABLE CARD(
   CARD_ID INT PRIMARY KEY,
   ACCOUNT_ID INT NOT NULL,
   CARD_NUMBER VARCHAR2(16) NOT NULL UNIQUE CHECK(LENGTH(CARD_NUMBER) = 16),
   CARD_TYPE VARCHAR2(20) NOT NULL CHECK (CARD_TYPE IN ('Debit', 'Credit', 'Prepaid')),
   ISSUED_DATE DATE DEFAULT SYSDATE,
   EXPIRY_DATE DATE NOT NULL,
   STATUS VARCHAR2(20) DEFAULT 'Active' CHECK (STATUS IN ('Active', 'Blocked', 'Expired', 'Lost', 'Stolen')),
   DAILY_LIMIT DECIMAL(10,2) CHECK (DAILY_LIMIT > 0),
   CONSTRAINT FK_CARD_ACC FOREIGN KEY (ACCOUNT_ID) 
   REFERENCES ACCOUNT(ACCOUNT_ID) ON DELETE CASCADE,
   CONSTRAINT CHK_CARD_EXPIRY CHECK (EXPIRY_DATE > ISSUED_DATE)
);
-- =====================================================
-- TABLE: LOAN_TYPE
-- ===================================================
CREATE TABLE LOAN_TYPE(
   LOAN_TYPE_ID INT PRIMARY KEY,
   TYPE_NAME VARCHAR2(40) NOT NULL UNIQUE CHECK (TYPE_NAME IN ('Housing', 'Car')),
   PROFIT_RATE DECIMAL(5,2) NOT NULL CHECK (PROFIT_RATE > 0),
   MAX_DURATION_MONTHS INT NOT NULL CHECK (MAX_DURATION_MONTHS > 0),
   MIN_AMOUNT DECIMAL(15,2),
   MAX_AMOUNT DECIMAL(15,2)
);
-- =====================================================
-- TABLE: LOAN APPLICATION
-- ===================================================
CREATE TABLE LOAN_APPLICATION(
   APPLICATION_ID INT PRIMARY KEY,
   CUSTOMER_ID INT NOT NULL,
   BRANCH_ID INT NOT NULL,
   LOAN_TYPE_ID INT NOT NULL,
   REQUESTED_AMOUNT DECIMAL(15,2) NOT NULL CHECK (REQUESTED_AMOUNT > 0),
   STATUS VARCHAR2(30) DEFAULT 'Pending' CHECK (STATUS IN ('Pending', 'Under Review', 'Approved', 'Rejected')),
   APPLICATION_DATE DATE DEFAULT SYSDATE,
   EVALUATION_DATE DATE,
   CONSTRAINT FK_LAPP_CUST FOREIGN KEY (CUSTOMER_ID) 
   REFERENCES CUSTOMER(CUSTOMER_ID),
   CONSTRAINT FK_LAPP_BRANCH FOREIGN KEY (BRANCH_ID) 
   REFERENCES BRANCH(BRANCH_ID),
   CONSTRAINT FK_LAPP_TYPE FOREIGN KEY (LOAN_TYPE_ID) 
   REFERENCES LOAN_TYPE(LOAN_TYPE_ID)
);

-- =====================================================
-- TABLE: LOAN ACCOUNT
-- ===================================================
CREATE TABLE LOAN_ACCOUNT(
   LOAN_ACCOUNT_ID INT PRIMARY KEY,
   CUSTOMER_ID INT NOT NULL,
   BRANCH_ID INT NOT NULL,
   LOAN_TYPE_ID INT NOT NULL,
   PRINCIPAL_AMOUNT DECIMAL(15,2) NOT NULL CHECK (PRINCIPAL_AMOUNT > 0),
   PROFIT_RATE DECIMAL(5,2) NOT NULL CHECK (PROFIT_RATE > 0),
   START_DATE DATE DEFAULT SYSDATE,
   DURATION_MONTHS INT NOT NULL CHECK (DURATION_MONTHS > 0),
   EXPECTED_END_DATE DATE NOT NULL,
   ACTUAL_END_DATE DATE,
   BALANCE_REMAINING DECIMAL(15,2) NOT NULL CHECK (BALANCE_REMAINING >= 0),
   STATUS VARCHAR2(20) DEFAULT 'Active' CHECK (STATUS IN ('Active', 'Closed', 'Defaulted', 'Written Off')),
   CONSTRAINT FK_LACC_CUST FOREIGN KEY (CUSTOMER_ID) 
   REFERENCES CUSTOMER(CUSTOMER_ID),
   CONSTRAINT FK_LACC_BRANCH FOREIGN KEY (BRANCH_ID) 
   REFERENCES BRANCH(BRANCH_ID),
   CONSTRAINT FK_LACC_TYPE FOREIGN KEY (LOAN_TYPE_ID) 
   REFERENCES LOAN_TYPE(LOAN_TYPE_ID)
);

-- =====================================================
-- TABLE: LOAN REPAYMENT
-- ===================================================
CREATE TABLE LOAN_REPAYMENT(
   LOAN_REPAYMENT_ID INT PRIMARY KEY,
   LOAN_ACCOUNT_ID INT NOT NULL,
   PAYMENT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   AMOUNT_PAID DECIMAL(15,2) NOT NULL CHECK (AMOUNT_PAID > 0),
   PRINCIPAL_COMPONENT DECIMAL(15,2) NOT NULL CHECK (PRINCIPAL_COMPONENT >= 0),
   PROFIT_COMPONENT DECIMAL(15,2) NOT NULL CHECK (PROFIT_COMPONENT >= 0),
   PAYMENT_METHOD VARCHAR2(30) CHECK (PAYMENT_METHOD IN ('Cash', 'Cheque', 'Auto-debit', 'Online', 'Transfer')),
   INSTALLMENT_NUMBER INT,   
   CONSTRAINT FK_REPAY_LACC FOREIGN KEY (LOAN_ACCOUNT_ID) 
   REFERENCES LOAN_ACCOUNT(LOAN_ACCOUNT_ID) ON DELETE CASCADE,
   CONSTRAINT CHK_REPAY_SUM CHECK (AMOUNT_PAID = PRINCIPAL_COMPONENT + PROFIT_COMPONENT)
);

-- =====================================================
-- TABLE: LOCKER
-- ===================================================
CREATE TABLE LOCKER(
   LOCKER_ID INT PRIMARY KEY,
   BRANCH_ID INT NOT NULL,
   LOCKER_NUMBER VARCHAR2(20) NOT NULL,
   LOCKER_SIZE VARCHAR2(20) CHECK (LOCKER_SIZE IN ('Small', 'Medium', 'Large')),
   ANNUAL_FEE DECIMAL(10,2),
   STATUS VARCHAR2(30) DEFAULT 'Available' CHECK (STATUS IN ('Available', 'Occupied', 'Under Maintenance')),  
   CONSTRAINT FK_LOCKER_BRANCH FOREIGN KEY (BRANCH_ID) 
   REFERENCES BRANCH(BRANCH_ID),
   CONSTRAINT UQ_LOCKER_NUM UNIQUE (BRANCH_ID, LOCKER_NUMBER)
);

-- =====================================================
-- TABLE: LOCKER_RENTAL
-- ===================================================
CREATE TABLE LOCKER_RENTAL(
   RENTAL_ID INT PRIMARY KEY,
   LOCKER_ID INT NOT NULL,
   ACCOUNT_ID INT NOT NULL,
   START_DATE DATE DEFAULT SYSDATE,
   END_DATE DATE NOT NULL,
   STATUS VARCHAR2(20) DEFAULT 'Active' CHECK (STATUS IN ('Active', 'Expired', 'Cancelled')),
   CONSTRAINT FK_RENTAL_LOCKER FOREIGN KEY (LOCKER_ID) 
   REFERENCES LOCKER(LOCKER_ID),
   CONSTRAINT FK_RENTAL_ACC FOREIGN KEY (ACCOUNT_ID) 
   REFERENCES ACCOUNT(ACCOUNT_ID) ON DELETE CASCADE,
   CONSTRAINT CHK_RENTAL_DATES CHECK (END_DATE > START_DATE)
);

-- =====================================================
-- CREATE TRIGGERS 
-- =====================================================

-- Auto-increment trigger
CREATE OR REPLACE TRIGGER customer_bir
    BEFORE INSERT ON CUSTOMER FOR EACH ROW
BEGIN
    IF :new.CUSTOMER_ID IS NULL THEN
        SELECT customer_seq.NEXTVAL INTO :new.CUSTOMER_ID FROM dual;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER user_auth_bir
    BEFORE INSERT ON USER_AUTH FOR EACH ROW
BEGIN
    IF :new.USER_ID IS NULL THEN
        SELECT user_auth_seq.NEXTVAL INTO :new.USER_ID FROM dual;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER branch_bir
    BEFORE INSERT ON BRANCH FOR EACH ROW
BEGIN
    IF :new.BRANCH_ID IS NULL THEN
        SELECT branch_seq.NEXTVAL INTO :new.BRANCH_ID FROM dual;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER account_type_bir
    BEFORE INSERT ON ACCOUNT_TYPE FOR EACH ROW
BEGIN
    IF :new.TYPE_ID IS NULL THEN
        SELECT account_type_seq.NEXTVAL INTO :new.TYPE_ID FROM dual;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER account_bir
    BEFORE INSERT ON ACCOUNT FOR EACH ROW
BEGIN
    IF :new.ACCOUNT_ID IS NULL THEN
        SELECT account_seq.NEXTVAL INTO :new.ACCOUNT_ID FROM dual;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER transaction_bir
    BEFORE INSERT ON BANK_TRANSACTION FOR EACH ROW
BEGIN
    IF :new.TRANSACTION_ID IS NULL THEN
        SELECT transaction_seq.NEXTVAL INTO :new.TRANSACTION_ID FROM dual;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER card_bir
    BEFORE INSERT ON CARD FOR EACH ROW
BEGIN
    IF :new.CARD_ID IS NULL THEN
        SELECT card_seq.NEXTVAL INTO :new.CARD_ID FROM dual;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER loan_type_bir
    BEFORE INSERT ON LOAN_TYPE FOR EACH ROW
BEGIN
    IF :new.LOAN_TYPE_ID IS NULL THEN
        SELECT loan_type_seq.NEXTVAL INTO :new.LOAN_TYPE_ID FROM dual;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER loan_application_bir
    BEFORE INSERT ON LOAN_APPLICATION FOR EACH ROW
BEGIN
    IF :new.APPLICATION_ID IS NULL THEN
        SELECT loan_application_seq.NEXTVAL INTO :new.APPLICATION_ID FROM dual;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER loan_account_bir
    BEFORE INSERT ON LOAN_ACCOUNT FOR EACH ROW
BEGIN
    IF :new.LOAN_ACCOUNT_ID IS NULL THEN
        SELECT loan_account_seq.NEXTVAL INTO :new.LOAN_ACCOUNT_ID FROM dual;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER loan_repayment_bir
    BEFORE INSERT ON LOAN_REPAYMENT FOR EACH ROW
BEGIN
    IF :new.LOAN_REPAYMENT_ID IS NULL THEN
        SELECT loan_repayment_seq.NEXTVAL INTO :new.LOAN_REPAYMENT_ID FROM dual;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER locker_bir
    BEFORE INSERT ON LOCKER FOR EACH ROW
BEGIN
    IF :new.LOCKER_ID IS NULL THEN
        SELECT locker_seq.NEXTVAL INTO :new.LOCKER_ID FROM dual;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER locker_rental_bir
    BEFORE INSERT ON LOCKER_RENTAL FOR EACH ROW
BEGIN
    IF :new.RENTAL_ID IS NULL THEN
        SELECT locker_rental_seq.NEXTVAL INTO :new.RENTAL_ID FROM dual;
    END IF;
END;
/

-- Business Logic Triggers
CREATE OR REPLACE TRIGGER calculate_age_trigger
    BEFORE INSERT OR UPDATE OF DATE_OF_BIRTH ON CUSTOMER
    FOR EACH ROW
BEGIN
    :new.AGE := TRUNC(MONTHS_BETWEEN(SYSDATE, :new.DATE_OF_BIRTH) / 12);
END;
/

CREATE OR REPLACE TRIGGER generate_account_number
    BEFORE INSERT ON ACCOUNT
    FOR EACH ROW
BEGIN
    IF :new.ACCOUNT_NUMBER IS NULL THEN
        SELECT 'ACC' || TO_CHAR(account_seq.NEXTVAL) 
        INTO :new.ACCOUNT_NUMBER FROM dual;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER generate_card_number
    BEFORE INSERT ON CARD
    FOR EACH ROW
BEGIN
    IF :new.CARD_NUMBER IS NULL THEN
        SELECT LPAD(card_seq.NEXTVAL, 16, '0') 
        INTO :new.CARD_NUMBER FROM dual;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER update_loan_balance
    AFTER INSERT ON LOAN_REPAYMENT
    FOR EACH ROW
BEGIN
    UPDATE LOAN_ACCOUNT 
    SET BALANCE_REMAINING = BALANCE_REMAINING - :new.PRINCIPAL_COMPONENT
    WHERE LOAN_ACCOUNT_ID = :new.LOAN_ACCOUNT_ID;
END;
/

-- =====================================================
-- INSERT SAMPLE DATA 
-- =====================================================

--  Branches
INSERT INTO BRANCH (BRANCH_NAME, LOCATION) VALUES ('Main Branch', 'City Center');
INSERT INTO BRANCH (BRANCH_NAME, LOCATION) VALUES ('North Branch', 'North Area');
INSERT INTO BRANCH (BRANCH_NAME, LOCATION) VALUES ('South Branch', 'South Area');

--  Account Types
INSERT INTO ACCOUNT_TYPE (TYPE_NAME, MIN_BALANCE, MONTHLY_FEE) 
VALUES ('Savings Account', 1000, 0);
INSERT INTO ACCOUNT_TYPE (TYPE_NAME, MIN_BALANCE, MONTHLY_FEE) 
VALUES ('Current Account', 5000, 100);
INSERT INTO ACCOUNT_TYPE (TYPE_NAME, MIN_BALANCE, MONTHLY_FEE) 
VALUES ('Islamic Account', 2000, 0);

--  Loan Types
INSERT INTO LOAN_TYPE (TYPE_NAME, PROFIT_RATE, MAX_DURATION_MONTHS, MIN_AMOUNT, MAX_AMOUNT)
VALUES ('Housing', 5.5, 360, 500000, 50000000);
INSERT INTO LOAN_TYPE (TYPE_NAME, PROFIT_RATE, MAX_DURATION_MONTHS, MIN_AMOUNT, MAX_AMOUNT)
VALUES ('Car', 7.2, 60, 500000, 5000000);

--  10 Customers (with ages over 18)
INSERT INTO CUSTOMER (CNIC, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, ADDRESS, EMAIL) 
VALUES ('1234567890123', 'Ahmed', 'Khan', TO_DATE('1990-01-15', 'YYYY-MM-DD'), '03001234567', 'House 1, Street 2, Karachi', 'ahmed.khan@example.com');

INSERT INTO CUSTOMER (CNIC, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, ADDRESS, EMAIL) 
VALUES ('2345678901234', 'Fatima', 'Ali', TO_DATE('1985-05-20', 'YYYY-MM-DD'), '03011234568', 'House 3, Street 4, Lahore', 'fatima.ali@example.com');

INSERT INTO CUSTOMER (CNIC, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, ADDRESS, EMAIL) 
VALUES ('3456789012345', 'Usman', 'Malik', TO_DATE('1982-08-10', 'YYYY-MM-DD'), '03021234569', 'House 5, Street 6, Islamabad', 'usman.malik@example.com');

INSERT INTO CUSTOMER (CNIC, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, ADDRESS, EMAIL) 
VALUES ('4567890123456', 'Ayesha', 'Rehman', TO_DATE('1988-12-05', 'YYYY-MM-DD'), '03031234570', 'House 7, Street 8, Rawalpindi', 'ayesha.rehman@example.com');

INSERT INTO CUSTOMER (CNIC, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, ADDRESS, EMAIL) 
VALUES ('5678901234567', 'Bilal', 'Ahmed', TO_DATE('1985-03-25', 'YYYY-MM-DD'), '03041234571', 'House 9, Street 10, Faisalabad', 'bilal.ahmed@example.com');

INSERT INTO CUSTOMER (CNIC, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, ADDRESS, EMAIL) 
VALUES ('6789012345678', 'Sara', 'Khan', TO_DATE('1991-07-14', 'YYYY-MM-DD'), '03051234572', 'House 11, Street 12, Peshawar', 'sara.khan@example.com');

INSERT INTO CUSTOMER (CNIC, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, ADDRESS, EMAIL) 
VALUES ('7890123456789', 'Omar', 'Shah', TO_DATE('1987-11-30', 'YYYY-MM-DD'), '03061234573', 'House 13, Street 14, Quetta', 'omar.shah@example.com');

INSERT INTO CUSTOMER (CNIC, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, ADDRESS, EMAIL) 
VALUES ('8901234567890', 'Zainab', 'Hussain', TO_DATE('1983-04-18', 'YYYY-MM-DD'), '03071234574', 'House 15, Street 16, Multan', 'zainab.hussain@example.com');

INSERT INTO CUSTOMER (CNIC, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, ADDRESS, EMAIL) 
VALUES ('9012345678901', 'Kamran', 'Butt', TO_DATE('1979-09-22', 'YYYY-MM-DD'), '03081234575', 'House 17, Street 18, Gujranwala', 'kamran.butt@example.com');

INSERT INTO CUSTOMER (CNIC, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PHONE_NUMBER, ADDRESS, EMAIL) 
VALUES ('0123456789012', 'Nadia', 'Akhtar', TO_DATE('1984-06-08', 'YYYY-MM-DD'), '03091234576', 'House 19, Street 20, Sialkot', 'nadia.akhtar@example.com');

-- Insert User Auth for customers (using actual customer IDs that were generated)
INSERT INTO USER_AUTH (CUSTOMER_ID, PASSWORD_HASH, STATUS) 
SELECT CUSTOMER_ID, '$2b$12$p/8tjQynfnXRPujl1wCzI.siIYrqdfMxsl0JqWtZnG9Ws8lJip14S', 'Active' 
FROM CUSTOMER;

COMMIT;

-- =====================================================
-- VERIFICATION QUERIES
-- =====================================================

-- Verify tables were created
SELECT table_name FROM user_tables ORDER BY table_name;

-- Verify customer data with ages
SELECT CUSTOMER_ID, FIRST_NAME, LAST_NAME, CNIC, AGE FROM CUSTOMER;

-- Verify user auth data
SELECT u.USER_ID, c.FIRST_NAME, c.LAST_NAME, u.STATUS 
FROM USER_AUTH u 
JOIN CUSTOMER c ON u.CUSTOMER_ID = c.CUSTOMER_ID;

SELECT 'Retail Banking Schema setup completed successfully!' AS status FROM dual;