SELECT 
    a.BALANCE,
    c.CARD_NUMBER,
    cust.FIRST_NAME || ' ' || cust.LAST_NAME AS full_name
FROM ACCOUNT a
JOIN ACCOUNT_HOLDER ah ON a.ACCOUNT_ID = ah.ACCOUNT_ID
JOIN USER_AUTH ua ON ah.CUSTOMER_ID = ua.CUSTOMER_ID
JOIN CUSTOMER cust ON cust.CUSTOMER_ID = ah.CUSTOMER_ID
JOIN CARD c ON c.ACCOUNT_ID = a.ACCOUNT_ID
WHERE ua.USER_ID = :user_id
  AND ah.HOLDER_TYPE = 'Primary';


SELECT  
   TRANSACTION_TYPE, 
   TRANSACTION_MODE, 
   AMOUNT, 
   RECIPIENT_ACCOUNT_NAME, 
   BALANCE_REMAINING, 
   TRANSACTION_DATE 
FROM BANK_TRANSACTION 
WHERE ACCOUNT_ID = ( 
   SELECT ACCOUNT_ID 
   FROM ACCOUNT_HOLDER ah 
   JOIN USER_AUTH ua ON ah.CUSTOMER_ID = ua.CUSTOMER_ID 
   WHERE ua.USER_ID = :user_id 
) 
ORDER BY TRANSACTION_DATE DESC; 
 
SELECT  
   l.LOCKER_NUMBER, 
   l.LOCKER_SIZE, 
   lr.START_DATE, 
   lr.END_DATE, 
   lr.STATUS 
FROM LOCKER_RENTAL lr 
JOIN LOCKER l ON lr.LOCKER_ID = l.LOCKER_ID 
JOIN ACCOUNT a ON lr.ACCOUNT_ID = a.ACCOUNT_ID 
JOIN ACCOUNT_HOLDER ah ON a.ACCOUNT_ID = ah.ACCOUNT_ID 
JOIN USER_AUTH ua ON ah.CUSTOMER_ID = ua.CUSTOMER_ID 
WHERE ua.USER_ID = :user_id; 
 
 

SELECT  
   LOCKER_ID, 
   LOCKER_NUMBER, 
   LOCKER_SIZE, 
   ANNUAL_FEE, 
   BRANCH_ID 
FROM LOCKER 
WHERE STATUS = 'Available'; 

 

SELECT  
   la.APPLICATION_DATE, 
   lt.TYPE_NAME, 
   la.REQUESTED_AMOUNT, 
   la.STATUS 
FROM LOAN_APPLICATION la 
JOIN LOAN_TYPE lt ON la.LOAN_TYPE_ID = lt.LOAN_TYPE_ID 
WHERE la.CUSTOMER_ID = :user_id 
ORDER BY la.APPLICATION_DATE DESC;

select *from card;